### ISSUE TITLE
save dumped packets somewhere to provide as fixtures for everyone

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/prismarine-packet-dumper#6]

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-packet-dumper/tree/fixtures/packets/from-server here are some
will put per version somewhere once it's a bit better

**Comment by u9g** [comment]
maybe we call it prismarine-packets and follow a similar naming scheme to mcdata?

**Comment by rom1504** [comment]
`minecraft-protocol-fixtures` could be the name of the repo to store that data

**Comment by rom1504** [comment]
yeah `minecraft-packets` is good too

**Comment by u9g** [comment]
can be closed, solved by https://github.com/PrismarineJS/minecraft-packets
